[tox]
envlist = py310,py311,py312,py313,py314,py315,py315t,py314t,pypy3,coverage

[testenv]
extras =
     test
commands =
         zope-testrunner --test-path=src  --auto-color --auto-progress [] # substitute with tox positional args

[testenv:coverage]
usedevelop = true
setenv =
    PURE_PYTHON = 1
basepython =
    python3
commands =
    coverage run -m zope.testrunner --test-path=src []
    coverage report --fail-under=100
deps =
    coverage


[testenv:py314t]
setenv:
    PYTHON_GIL=0

[testenv:py315t]
setenv:
    PYTHON_GIL=0

[testenv:docs]
commands =
    sphinx-build -b html -d docs/_build/doctrees docs docs/_build/html
extras =
    docs
